version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: churnguard_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: churnguard_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/churn_db
      - SECRET_KEY=churnguard_super_secret_key_2026
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: churnguard_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
